export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ADD_SUBJECT_SUCCESS = "ADD_SUBJECT_SUCCESS";
export const ADD_SUBJECT_FAIL = "ADD_SUBJECT_FAIL";

export const JUDGE_SUBJECT_SUCCESS = "JUDGE_SUBJECT_SUCCESS";
export const JUDGE_SUBJECT_FAIL = "JUDGE_SUBJECT_FAIL";

export const PRO_SUBJECT_SUCCESS = "PRO_SUBJECT_SUCCESS";
export const PRO_SUBJECT_FAIL = "PRO_SUBJECT_FAIL";

export const CAMPUS_SUBJECT_SUCCESS = "CAMPUS_SUBJECT_SUCCESS";
export const CAMPUS_SUBJECT_FAIL = "CAMPUS_SUBJECT_FAIL";

export const COPRO_SUBJECT_SUCCESS = "COPRO_SUBJECT_SUCCESS";
export const COPRO_SUBJECT_FAIL = "COPRO_SUBJECT_FAIL";

export const RGG_SUBJECT_SUCCESS = "RGG_SUBJECT_SUCCESS";
export const RGG_SUBJECT_FAIL = "RGG_SUBJECT_FAIL";

export const SHOW_SUBJECT_SUCCESS = "SHOW_SUBJECT_SUCCESS";
export const SHOW_SUBJECT_FAIL = "SHOW_SUBJECT_FAIL";

export const TARGET_SUBJECT_SUCCESS = "TARGET_SUBJECT_SUCCESS";
export const TARGET_SUBJECT_FAIL = "TARGET_SUBJECT_FAIL";

export const POST_TOP3_SUCCESS= "POST_TOP3_SUCCESS";
export const POST_TOP3_FAIL = "POST_TOP3_FAIL";